apiVersion: apps/v1
kind: Deployment
metadata:
  name: canteen-client
  namespace: "{{ .Values.tumid }}-devops26"
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: canteen-client-selector
  template:
    metadata:
      annotations:
        checksum/app-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: canteen-client-selector
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          env:
            - name: PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api_url
